kind: "EntandoApp"
apiVersion: "entando.org/v1"
metadata:
  name: "{{ .Release.Name }}"
  annotations:
    entando.org/operator-id: {{ .Values.app.operatorId }}
entandoStatus:
  entandoDeploymentPhase: "ignored"
spec:
  dbms: "{{ .Values.app.dbms }}"
  replicas: 1
  {{- if .Values.app.singleHostName }}
  ingressHostName: "{{- .Values.app.singleHostName }}"
  {{- end }}
  standardServerImage: wildfly
  resourceRequirements:
    storageRequest: 1Gi
    storageLimit: 2Gi
    memoryRequest: 128Mi
    memoryLimit: 1Gi
    cpuRequest: 64m
    cpuLimit: 1000m
    fileUploadLimit: 500m
