kind: "EntandoAppPluginLink"
apiVersion: "entando.org/v1"
metadata:
  name: "{{ .Release.Name }}-{{ .Values.plugin.name }}-link"
entandoStatus:
  entandoDeploymentPhase: "ignored"
spec:
  entandoAppName: "{{ .Release.Name }}"
  entandoPluginName: "{{ .Values.plugin.name }}"
